# # Étape 1 : PHP avec Apache
# FROM php:8.2-apache

# # Installer Node.js et npm
# RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
#     && apt-get install -y nodejs

# # Installer extensions PHP
# RUN apt-get update && apt-get install -y \
#     git unzip curl libpng-dev libonig-dev libxml2-dev zip \
#     && docker-php-ext-install pdo pdo_mysql mbstring exif pcntl bcmath gd

# RUN a2enmod rewrite

# # Copier code
# COPY . /var/www/html

# RUN chown -R www-data:www-data /var/www/html \
#     && chmod -R 755 /var/www/html

# COPY ./docker/apache.conf /etc/apache2/sites-available/000-default.conf

# COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# # Installer Laravel + assets
# RUN composer install --no-interaction \
#     && npm install \
#     && npm run build

# EXPOSE 80




FROM php:8.4-apache

# Dépendances système + extensions PHP
RUN apt-get update && apt-get install -y \
    git unzip curl zip \
    libpng-dev libonig-dev libxml2-dev \
    && docker-php-ext-install pdo pdo_mysql mbstring gd \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Apache rewrite
RUN a2enmod rewrite

# Composer (sans image externe)
RUN curl -sS https://getcomposer.org/installer \
    | php -- --install-dir=/usr/local/bin --filename=composer

# Node.js 18
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
    && apt-get install -y nodejs

WORKDIR /var/www/html

# 👉 Copier TOUT le projet AVANT composer install
COPY . .

# Installer dépendances Laravel + front
#RUN composer install --no-interaction --prefer-dist \
#    && npm install \
#    && npm run buildversion: '3.1'

# Permissions Laravel
RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 775 storage bootstrap/cache

EXPOSE 80




#jnthnkabongo/ebar